####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: {{ default .Values.meta.name (.Values.service).name }}
  labels:
    application: {{ .Values.meta.name | quote }}

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: {{ .Values.meta.name | quote }}

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: amqp
      port: {{ .Values.ports.amqp }}
      targetPort: 5672

    - name: mgmt
      port: {{ .Values.ports.mgmt }}
      targetPort: 15672
